### ISSUE TITLE
Fix Viewing Document Resources

### ISSUE THREAD

**Issue by Boyan-Apostolov** [Berat-Dzhevdetov/DeemZ-Platform#10]
Currently throws exception SqlNullValueException: Data is Null. This method or property cannot be called on Null values when trying to get context.Resources

**Comment by Berat-Dzhevdetov** [comment]
Can you give more context of what is happening?

**Comment by Boyan-Apostolov** [comment]
no

**Comment by Boyan-Apostolov** [comment]
Issue already fixed.
