### ISSUE TITLE
Refactor controller checks to avoid duplicate code

### ISSUE THREAD

**Issue by Boyan-Apostolov** [Berat-Dzhevdetov/DeemZ-Platform#13]
Make a base class for example with all the necessary checks. Avoid using !examService.GetExamById(examId) and guard.AgainstNull(examId...) in every method

**Comment by Berat-Dzhevdetov** [comment]
How about creating a filter that will be called before performing an action and with reflection to take the parameters of the action and check them for null? This should save a lot of code and repeatability.

**Comment by Boyan-Apostolov** [comment]
Great idea!

**Comment by Berat-Dzhevdetov** [comment]
Made a filter that checks if there is an entity with a given id in the database.
