### ISSUE TITLE
Code repeatability for redirecting

### ISSUE THREAD

**Issue by Berat-Dzhevdetov** [Berat-Dzhevdetov/DeemZ-Platform#14]
We need to figure out a way to redirect to the error pages with our error handling to avoid code repetition:

```CSharp
var errorModel = new HandleErrorModel
{
    Message = AccessDenied,
    StatusCode = Models.HttpStatusCodes.Forbidden
};

TempData[ErrorMessageKey] = JsonConvert.SerializeObject(errorModel);

return RedirectToAction(nameof(HomeController.UserErrorPage), typeof(HomeController).GetControllerName());

```

**Comment by Boyan-Apostolov** [comment]
SOLUTION FOUND!!! (tested and working)

Create a BaseController Class containing the following logic :

```CSharp
public IActionResult HandleErrorRedirect()
        {
            var errorModel = new HandleErrorModel
            {
                Message = AccessDenied,
                StatusCode = Models.HttpStatusCodes.Forbidden
            };
                TempData[ErrorMessageKey] = JsonConvert.SerializeObject(errorModel);
            return RedirectToAction(nameof(HomeController.UserErrorPage), typeof(HomeController).GetControllerName());
        }
```
In the other controllers where you want to remove the duplicate code you have stated in the previous message, now you can use
`return RedirectToAction(nameof(BaseController.HandleErrorRedirect),typeof(BaseController).GetControllerName());`
in the body of the If ( check ).

Currently, we only use 'AccessDenied' as an error message so this method works perfectly. We can easily extend it if we want more error messages:)

The code is not yet committed as I need your approval ;3

**Comment by Berat-Dzhevdetov** [comment]
Which do you think would be better to make one method that accepts the status code or many methods that are for different status codes? It also means going through all the controllers and making the change.

**Comment by Boyan-Apostolov** [comment]
Maybe one method which accepts the error  code and then chooses what message to display in the error page.
2nd, of course we need to change in every controller, but it will be one line, not like now when it's return BadRequest, forbidden etc..

**Comment by Berat-Dzhevdetov** [comment]
I like your idea well! Make the changes.

**Comment by Boyan-Apostolov** [comment]
--- CHANGES IMPLEMENTED ---
