### ISSUE TITLE
Email sender

### ISSUE THREAD

**Issue by Berat-Dzhevdetov** [Berat-Dzhevdetov/DeemZ-Platform#21]
To do when a user registers in the application to send a confirmation email. Also, send him an email when he successfully registers for a new course.

**Comment by Boyan-Apostolov** [comment]
Implemented Email Sender with the help of the SendGrid API, emails will be sent after successful payment. Any suggestions where also to send emails?

**Comment by Berat-Dzhevdetov** [comment]
Great job! You can make a separate page in the admin panel where we can send emails to everyone at once. In order to notify them when there is a new upcoming sign up session or something like that.

**Comment by Boyan-Apostolov** [comment]
Change Personalizations to sending different emails so that the users don't see the other recipients
![Screenshot 2021-09-19 201553](https://user-images.githubusercontent.com/58187770/133936631-ecc961c2-8741-48f2-b25f-3649d043f932.png)

**Comment by Boyan-Apostolov** [comment]
@Berat-Dzhevdetov please find a method to select users and send the email to them :)

**Comment by Boyan-Apostolov** [comment]
Never mind, I found a way to select the users with JS and send the list to the controller!

_FEATURE IMPLEMENTED_
