### ISSUE TITLE
Real time chatting between the lecture and the students. 

### ISSUE THREAD

**Issue by Berat-Dzhevdetov** [Berat-Dzhevdetov/DeemZ-Platform#23]
Let's create an online platform in which students during online lectures can ask the lecturer things they did not understand or for additional information. Students will have a join button after which an virtual room will open in which they will be able to write. Messages will be visible to everyone to like, dislike and sorted by sent time, but only the administrator will be able to delete them. When you press the join button we will hook in the header hashed user id and the roomId/secret key. The front end will need to save the data and send it to the server with each request so that the server can authorize the user and his secret key. The front end can be done on Angular for the better UX. Angular will use a controller that is made as the endpoint of the application. The two sides will communicate through JSON.

**Comment by Berat-Dzhevdetov** [comment]
I suggest removing the join page. We can simply make the connection request in the content component in the constructor.

**Comment by Boyan-Apostolov** [comment]
Great suggestion! I also think we don't need the join page. I will get right to it shortly! Meanwhile, can you figure a way to send the profile pictures of the messages' authors? It will also be really helpful if you could fix, the design of the new OPEN CHAT BUTTON in the course page!

**Comment by Berat-Dzhevdetov** [comment]
Let's make the admin be able to delete all the other messages with one button and to see the admin that the messages are really deleting let's make a loader. He will initially take all the number of comments we have in the database and will count how many of them were deleted. We will divide the number of deleted by all and multiply by 100 to get the percentages. You can add it as a popup in some of the corners and write "deleting all messages" and load the loader below.

**Comment by Boyan-Apostolov** [comment]
Awesome! We can do this by using a loader or progress bar from the _[material design](https://material.angular.io/components/progress-bar/overview)_ or make one on our own

**Comment by Boyan-Apostolov** [comment]
We have finally managed to create a fully working real time application with Angular for the students in the different courses!

_Functionality implemented. Issue resolved_
