### ISSUE TITLE
Promo code for course

### ISSUE THREAD

**Issue by Berat-Dzhevdetov** [Berat-Dzhevdetov/DeemZ-Platform#28]
It just occurred to me that we could add promo codes to reduce the cost of the courses. The promo code will be applied when you enrol in a course. What do you think?

**Comment by Boyan-Apostolov** [comment]
Great idea! The user can get these promo codes from being the first to finish an exam with max points or win a giveaway from the admis!

**Comment by Berat-Dzhevdetov** [comment]
I implemented the all functionalities needed. Please make the functionality to send an email to the person with this username who has a promo code.

**Comment by Boyan-Apostolov** [comment]
Functionality added. Issue resolved.
